// <auto-generated />
using System;
using EldaraaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EldaraaApi.Migrations
{
    [DbContext(typeof(EldaraaDbContext))]
    [Migration("20250725202255_SeedInicial")]
    partial class SeedInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("EldaraaApi.Models.AtributoPersonalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sistema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonajeId");

                    b.ToTable("AtributosPersonalizados");
                });

            modelBuilder.Entity("EldaraaApi.Models.Civilizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Civilizaciones");
                });

            modelBuilder.Entity("EldaraaApi.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DadoGolpe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LanzadorConjuros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DadoGolpe = 12,
                            Descripcion = "El bárbaro es una fuerza bruta de la naturaleza. Canaliza su furia en combate, desatando una rabia salvaje que lo hace casi imposible de detener. Su conexión con el instinto lo vuelve resistente al dolor y letal con armas contundentes. No pelea por gloria, sino por supervivencia y orgullo tribal.",
                            LanzadorConjuros = false,
                            Nombre = "Bárbaro"
                        },
                        new
                        {
                            Id = 2,
                            DadoGolpe = 8,
                            Descripcion = "El bardo convierte la música, el arte y las palabras en magia pura. Domina una versatilidad asombrosa: puede inspirar a sus aliados, desatar hechizos o incluso engañar a la muerte con su carisma. Donde otros lanzan conjuros con libros o plegarias, el bardo lo hace con una canción.",
                            LanzadorConjuros = true,
                            Nombre = "Bardo"
                        },
                        new
                        {
                            Id = 3,
                            DadoGolpe = 8,
                            Descripcion = "Guerrero sagrado y servidor de lo divino, el clérigo canaliza el poder de su dios para sanar, proteger o castigar. Dependiendo de su dominio, puede ser un faro de vida, un martillo de guerra o un vengador implacable. Su fe es su arma más poderosa.",
                            LanzadorConjuros = true,
                            Nombre = "Clérigo"
                        },
                        new
                        {
                            Id = 4,
                            DadoGolpe = 8,
                            Descripcion = "Los druidas son guardianes del equilibrio natural. Controlan las fuerzas elementales, se transforman en bestias y convocan la furia de la tormenta o la calma del bosque. Su conexión con la tierra es profunda, y su sabiduría, ancestral.",
                            LanzadorConjuros = true,
                            Nombre = "Druida"
                        },
                        new
                        {
                            Id = 5,
                            DadoGolpe = 10,
                            Descripcion = "Maestro del combate marcial, el guerrero es versátil, disciplinado y peligroso con cualquier arma. Algunos luchan por honor, otros por oro, pero todos son fuerza pura en el campo de batalla. Su entrenamiento lo convierte en una máquina de guerra adaptable.",
                            LanzadorConjuros = false,
                            Nombre = "Guerrero"
                        },
                        new
                        {
                            Id = 6,
                            DadoGolpe = 6,
                            Descripcion = "A diferencia de los magos, los hechiceros nacen con la magia en la sangre. Su poder es innato, salvaje y muchas veces impredecible. Canalizan energías caóticas con pura fuerza de voluntad, y su conexión mágica suele tener un origen misterioso o ancestral.",
                            LanzadorConjuros = true,
                            Nombre = "Hechicero"
                        },
                        new
                        {
                            Id = 7,
                            DadoGolpe = 6,
                            Descripcion = "El mago es un erudito de lo arcano. A través de años de estudio y práctica rigurosa, domina una vasta variedad de conjuros. Aunque físicamente débil, su conocimiento mágico puede alterar la realidad misma, desatar tormentas de fuego o viajar entre planos.",
                            LanzadorConjuros = true,
                            Nombre = "Mago"
                        },
                        new
                        {
                            Id = 8,
                            DadoGolpe = 8,
                            Descripcion = "El monje perfecciona su cuerpo y mente hasta convertirlos en armas. Con una disciplina inquebrantable, puede golpear con velocidad fulminante, caminar por paredes o canalizar su ki para defenderse del daño. Es la encarnación del equilibrio interior.",
                            LanzadorConjuros = false,
                            Nombre = "Monje"
                        },
                        new
                        {
                            Id = 9,
                            DadoGolpe = 10,
                            Descripcion = "Guardián de lo sagrado, el paladín jura votos que lo vinculan a una causa o deidad. Sus habilidades combinan fuerza marcial con poder divino: cura heridas, destruye el mal y resiste la corrupción con una voluntad inquebrantable. Su fe es su escudo.",
                            LanzadorConjuros = true,
                            Nombre = "Paladín"
                        },
                        new
                        {
                            Id = 10,
                            DadoGolpe = 8,
                            Descripcion = "Ágil, astuto y letal en la sombra, el pícaro domina el sigilo, el engaño y los golpes certeros. Es el primero en entrar y el último en ser visto. Ya sea un ladrón callejero o un espía refinado, el pícaro convierte cada oportunidad en ventaja.",
                            LanzadorConjuros = false,
                            Nombre = "Pícaro"
                        },
                        new
                        {
                            Id = 11,
                            DadoGolpe = 10,
                            Descripcion = "El explorador es un cazador del mundo salvaje. Domina terrenos inhóspitos, sigue rastros imposibles y combate con eficacia donde otros apenas sobreviven. Muchos tienen compañeros animales y lanzan conjuros naturales para proteger sus dominios.",
                            LanzadorConjuros = true,
                            Nombre = "Explorador"
                        },
                        new
                        {
                            Id = 12,
                            DadoGolpe = 8,
                            Descripcion = "El brujo obtiene su poder mediante un pacto con una entidad poderosa: un demonio, un hada, un ente cósmico. Sus conjuros son limitados pero potentes, y sus habilidades oscuras lo convierten en un maestro del misterio y lo oculto. Su pacto es su fuerza... y su maldición.",
                            LanzadorConjuros = true,
                            Nombre = "Brujo"
                        });
                });

            modelBuilder.Entity("EldaraaApi.Models.EntradaLibre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonajeId");

                    b.ToTable("EntradasLibres");
                });

            modelBuilder.Entity("EldaraaApi.Models.Equipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("Propiedades")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipamientos");
                });

            modelBuilder.Entity("EldaraaApi.Models.EstadisticasCombate", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonoAtaqueConjuros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClaseArmadura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DadosGolpe")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DificultadSalvacionConjuros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HabilidadLanzamientoConjuros")
                        .HasColumnType("TEXT");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosGolpeActuales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosGolpeMaximos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Velocidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonajeId");

                    b.ToTable("EstadisticasCombate");
                });

            modelBuilder.Entity("EldaraaApi.Models.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HabilidadBase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HabilidadBase = "DEX",
                            Nombre = "Acrobacias"
                        },
                        new
                        {
                            Id = 2,
                            HabilidadBase = "INT",
                            Nombre = "Arcana"
                        },
                        new
                        {
                            Id = 3,
                            HabilidadBase = "STR",
                            Nombre = "Atletismo"
                        },
                        new
                        {
                            Id = 4,
                            HabilidadBase = "CHA",
                            Nombre = "Engaño"
                        },
                        new
                        {
                            Id = 5,
                            HabilidadBase = "INT",
                            Nombre = "Historia"
                        },
                        new
                        {
                            Id = 6,
                            HabilidadBase = "CHA",
                            Nombre = "Intimidación"
                        },
                        new
                        {
                            Id = 7,
                            HabilidadBase = "INT",
                            Nombre = "Investigación"
                        },
                        new
                        {
                            Id = 8,
                            HabilidadBase = "DEX",
                            Nombre = "Juego de manos"
                        },
                        new
                        {
                            Id = 9,
                            HabilidadBase = "WIS",
                            Nombre = "Medicina"
                        },
                        new
                        {
                            Id = 10,
                            HabilidadBase = "INT",
                            Nombre = "Naturaleza"
                        },
                        new
                        {
                            Id = 11,
                            HabilidadBase = "WIS",
                            Nombre = "Percepción"
                        },
                        new
                        {
                            Id = 12,
                            HabilidadBase = "WIS",
                            Nombre = "Perspicacia"
                        },
                        new
                        {
                            Id = 13,
                            HabilidadBase = "CHA",
                            Nombre = "Persuasión"
                        },
                        new
                        {
                            Id = 14,
                            HabilidadBase = "INT",
                            Nombre = "Religión"
                        },
                        new
                        {
                            Id = 15,
                            HabilidadBase = "DEX",
                            Nombre = "Sigilo"
                        },
                        new
                        {
                            Id = 16,
                            HabilidadBase = "WIS",
                            Nombre = "Supervivencia"
                        },
                        new
                        {
                            Id = 17,
                            HabilidadBase = "CHA",
                            Nombre = "Actuación"
                        });
                });

            modelBuilder.Entity("EldaraaApi.Models.Hechizo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alcance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Componentes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Escuela")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TiempoConjuro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hechizos");
                });

            modelBuilder.Entity("EldaraaApi.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("EldaraaApi.Models.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alineamiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCabello")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorOjos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorPiel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deidad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experiencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaPersonal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Inspiracion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreJugador")
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RazaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubrazaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrasfondoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("RazaId");

                    b.HasIndex("SubrazaId");

                    b.HasIndex("TrasfondoId");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("EldaraaApi.Models.PersonajeEquipamiento", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipamientoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Equipado")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonajeId", "EquipamientoId");

                    b.HasIndex("EquipamientoId");

                    b.ToTable("PersonajesEquipamiento");
                });

            modelBuilder.Entity("EldaraaApi.Models.PersonajeHabilidad", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Competente")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonajeId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("PersonajesHabilidad");
                });

            modelBuilder.Entity("EldaraaApi.Models.PersonajeHechizo", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HechizoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Preparado")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonajeId", "HechizoId");

                    b.HasIndex("HechizoId");

                    b.ToTable("PersonajesHechizo");
                });

            modelBuilder.Entity("EldaraaApi.Models.PuntuacionHabilidades", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitucion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Destreza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fuerza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sabiduria")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonajeId");

                    b.ToTable("PuntuacionesHabilidades");
                });

            modelBuilder.Entity("EldaraaApi.Models.RasgosPersonalidad", b =>
                {
                    b.Property<int>("PersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Defecto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ideal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rasgo1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rasgo2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vinculo")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonajeId");

                    b.ToTable("RasgosPersonalidades");
                });

            modelBuilder.Entity("EldaraaApi.Models.Raza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Razas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Los humanos son una raza de ambición desbordante, versátiles como ninguna otra y siempre empujando los límites de lo posible. Carecen de la longevidad de otras especies, pero compensan con una intensidad vital que los impulsa a construir imperios, descubrir secretos arcanos y desafiar a los propios dioses si es necesario. Su diversidad cultural es abrumadora: hay humanos que veneran lo arcano, otros que viven por la espada, y algunos que se guían solo por el comercio o la fe. Son el reflejo de lo mejor y lo peor del mundo.",
                            Nombre = "Humano"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Los elfos son seres de belleza etérea y alma longeva, cuya existencia está profundamente entrelazada con la magia y el equilibrio natural. Habitan bosques antiguos, torres cristalinas o reinos ocultos más allá del velo del mundo material. Para ellos, la paciencia es virtud, y los siglos les otorgan una sabiduría que otras razas solo pueden soñar. Viven con elegancia, se expresan con poesía, y sus movimientos parecen coreografiados por la danza de los vientos. Sin embargo, su perspectiva distante a veces los vuelve fríos ante los problemas urgentes del presente.",
                            Nombre = "Elfo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Nacidos de la roca y el fuego, los enanos son duros, tenaces y profundamente leales a su clan. Viven en fortalezas subterráneas forjadas en piedra y defendidas con acero, donde la historia de su linaje se graba en muros y crónicas. Su destreza en la herrería es legendaria, y sus armaduras y armas son codiciadas por reyes y aventureros. Son conocidos por su obstinación y su código de honor: una promesa enana es tan firme como la montaña. Sin embargo, su desconfianza hacia lo foráneo a veces los aísla, encerrándolos en sus propias fortalezas mentales y físicas.",
                            Nombre = "Enano"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Pequeños de estatura pero grandes de corazón, los medianos valoran la comodidad del hogar, las historias junto al fuego y la buena comida. Pero no se los debe subestimar: detrás de sus modales tranquilos hay una valentía inesperada y una suerte que raya lo sobrenatural. Suelen mantenerse alejados de las intrigas del mundo exterior, pero cuando uno de ellos deja su comarca, puede cambiar el destino del mundo. Su agilidad, discreción y naturaleza curiosa los vuelven compañeros ideales, y su inquebrantable optimismo es un faro en los tiempos oscuros.",
                            Nombre = "Mediano"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Los gnomos viven con una chispa inextinguible de entusiasmo. Son criaturas de mentes brillantes y corazones desbordantes de ideas. Amantes de los acertijos, la magia ilusoria y los dispositivos complejos, su vida es un constante experimento. Algunos gnomos se sumergen en la alquimia o la mecánica, mientras que otros encuentran gozo en el arte y la música. Son habladores, excéntricos y, a veces, exasperantes, pero nunca aburridos. Para un gnomo, el mundo es un lienzo por pintar o una máquina por desarmar... o ambas.",
                            Nombre = "Gnomo"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Nacidos del cruce entre elfos y humanos, los semielfos caminan entre mundos, sin pertenecer completamente a ninguno. Tienen la gracia y los sentidos agudos de sus ancestros élficos, junto con la pasión y ambición humanas. Su vida es un constante equilibrio entre lo que son y lo que podrían ser. Esta dualidad los vuelve carismáticos, diplomáticos por naturaleza y a menudo solitarios. Rechazados por algunos, idealizados por otros, los semielfos aprenden desde jóvenes a ser sus propios aliados y a forjar su identidad más allá del linaje.",
                            Nombre = "Semielfo"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Forjados en la violencia y la supervivencia, los semiorcos son descendientes de un legado feroz. Su fuerza física es impresionante, sus instintos combativos, agudos, y su presencia, imponente. Pero bajo esa fachada salvaje a menudo se esconde una lucha interna: una búsqueda de propósito, redención o simplemente aceptación. Muchos desafían el estigma que pesa sobre su sangre, demostrando que el honor, la compasión y el heroísmo no están limitados por el origen. Cuando un semiorco jura lealtad, su compromiso es absoluto y feroz como su furia ancestral.",
                            Nombre = "Semiorco"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Imponentes y majestuosos, los dracónidos son el eco de los dragones en forma humanoide. Portan escamas relucientes, ojos ardientes y un aura de poder ancestral. Su herencia se manifiesta no solo en su aliento elemental, sino en su porte y sentido del honor. Criados en sociedades rígidas con fuertes ideales de jerarquía y deber, muchos dracónidos buscan gloria para sí mismos o para sus clanes. Otros vagan por el mundo buscando comprender su conexión con los dragones antiguos. Son nobles, intensos y a menudo, solitarios portadores de un legado que arde en su sangre.",
                            Nombre = "Dracónido"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Marcados desde el nacimiento por pactos antiguos o linajes infernales, los tieflings portan la maldición de una sangre que no pidieron. Cuernos, ojos brillantes y colas serpenteantes los hacen blancos de prejuicio y temor, sin importar su carácter. Pero en la adversidad, los tieflings forjan voluntad de hierro. Muchos abrazan su herencia mágica y oscura, convirtiendo el rechazo en poder. Otros buscan redimirse o cambiar su destino. Bajo la piel infernal puede latir el corazón de un héroe, un villano... o algo mucho más complejo.",
                            Nombre = "Tiefling"
                        });
                });

            modelBuilder.Entity("EldaraaApi.Models.Subraza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RazaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RazaId");

                    b.ToTable("Subrazas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Los elfos de los bosques son rápidos, sigilosos y profundamente conectados con la naturaleza viva. Se desplazan por los árboles como sombras, y sus sentidos perciben lo que otros pasarían por alto. Prefieren la libertad de los caminos ocultos a la rigidez de los salones élficos.",
                            Nombre = "Elfo de los bosques",
                            RazaId = 2
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Orgullosos guardianes del saber mágico, los elfos altos veneran la tradición, el arte y la perfección arcana. Son los más cercanos a las antiguas cortes feéricas, y su dominio de la magia rivaliza con el de los magos humanos más renombrados.",
                            Nombre = "Elfo alto",
                            RazaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Criados en la oscuridad del inframundo, los drow son elfos marcados por una historia de traición, exilio y matriarcado implacable. Sus habilidades en combate, sigilo y magia oscura los hacen temibles, pero no todos siguen el camino de sus ancestros.",
                            Nombre = "Elfo oscuro (Drow)",
                            RazaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Fuertes de espíritu y resistentes al dolor, los enanos de las colinas valoran la tradición, la familia y los lazos ancestrales. Sus fortalezas están escondidas en valles protegidos, donde la sabiduría es tan preciada como el acero.",
                            Nombre = "Enano de las colinas",
                            RazaId = 3
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Más altos y robustos que sus parientes de las colinas, los enanos de las montañas son maestros de la guerra y la forja. Viven en fortalezas talladas en la piedra más dura, y sus clanes mantienen legados que se remontan a los albores del mundo.",
                            Nombre = "Enano de las montañas",
                            RazaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Ágiles y escurridizos, los piesligeros tienden a mezclarse con facilidad entre otras razas. Son curiosos, simpáticos y poseen una suerte natural que los salva de las situaciones más improbables.",
                            Nombre = "Mediano piesligeros",
                            RazaId = 4
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Más fuertes y robustos que otros medianos, los fornidos son sorprendentemente tenaces. Su resistencia física y voluntad férrea los hace ideales para las tareas más duras, a pesar de su pequeña estatura.",
                            Nombre = "Mediano fornido",
                            RazaId = 4
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Reclusivos, tímidos y misteriosos, los gnomos del bosque habitan en armonía con la naturaleza. Su magia proviene de la tierra misma, y muchos tienen vínculos con criaturas feéricas o espíritus del bosque.",
                            Nombre = "Gnomo del bosque",
                            RazaId = 5
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Inventores natos, los gnomos de las rocas son ingenieros, alquimistas y soñadores mecánicos. Sus madrigueras están repletas de artilugios chispeantes, libros de fórmulas y proyectos inacabados que podrían cambiar el mundo... o hacerlo explotar.",
                            Nombre = "Gnomo de las rocas",
                            RazaId = 5
                        });
                });

            modelBuilder.Entity("EldaraaApi.Models.Trasfondo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caracteristica")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trasfondos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caracteristica = "Refugio de la fe",
                            Descripcion = "Creciste en un templo, santuario o convento, consagrado al estudio y servicio de lo divino. Aprendiste rituales, escrituras y dogmas. Puedes refugiarte en cualquier templo de tu fe, y su gente suele ayudarte siempre que no contradigas tus votos.",
                            Nombre = "Acólito"
                        },
                        new
                        {
                            Id = 2,
                            Caracteristica = "Identidad falsa",
                            Descripcion = "Eres un maestro del engaño, con una red de identidades falsas y documentos falsificados. Tenés habilidades para manipular, disfrazarte y evadir la ley. Tu ingenio te mantiene con vida más que tu espada.",
                            Nombre = "Charlatán"
                        },
                        new
                        {
                            Id = 3,
                            Caracteristica = "Contacto criminal",
                            Descripcion = "Viviste al margen de la ley: ladrón, contrabandista, espía o asesino. Tenés una red de contactos en el mundo del crimen que puede ofrecerte información, refugio o favores... a cambio de algo.",
                            Nombre = "Criminal"
                        },
                        new
                        {
                            Id = 4,
                            Caracteristica = "Acceso a la fama",
                            Descripcion = "Tu vida es escenario: música, danza, teatro o acrobacias. Soñaste y viajaste mucho, dejando una pequeña estela de admiradores. Donde actúas, la gente te abre puertas y recuerda tu nombre.",
                            Nombre = "Artista ambulante"
                        },
                        new
                        {
                            Id = 5,
                            Caracteristica = "Hospitalidad rústica",
                            Descripcion = "De origen humilde, te convertiste en un líder local tras una hazaña. La gente sencilla te considera protector, y siempre encontrarás ayuda y refugio donde otros se niegan.",
                            Nombre = "Héroe del pueblo"
                        },
                        new
                        {
                            Id = 6,
                            Caracteristica = "Miembro del gremio",
                            Descripcion = "Fuiste formado en un oficio por un gremio reconocido. Esto te da privilegios legales, apoyo profesional y acceso a redes comerciales. Tu reputación te precede.",
                            Nombre = "Artesano del gremio"
                        },
                        new
                        {
                            Id = 7,
                            Caracteristica = "Revelación",
                            Descripcion = "Pasaste años en aislamiento buscando comprensión o redención. Encontraste una verdad secreta: un presagio, un arte arcano, una revelación espiritual. Ahora compartís tu sabiduría, pero te cuesta conectar con otros.",
                            Nombre = "Ermitaño"
                        },
                        new
                        {
                            Id = 8,
                            Caracteristica = "Pasaje marítimo",
                            Descripcion = "Has navegado mares, enfrentado tormentas y conocido puertos peligrosos. Sabés leer el cielo, escalar mástiles y sobrevivir en cubierta. La vida en alta mar te formó.",
                            Nombre = "Marinero"
                        },
                        new
                        {
                            Id = 9,
                            Caracteristica = "Investigador",
                            Descripcion = "Permaneciste entre libros, laboratorios o pergaminos, buscando respuestas. Tu mente es una biblioteca viviente. Las instituciones académicas te reconocen, aunque pueden verte como un excéntrico.",
                            Nombre = "Sabio"
                        },
                        new
                        {
                            Id = 10,
                            Caracteristica = "Rango militar",
                            Descripcion = "La guerra te formó: disciplina, estrategia y camaradería bajo fuego. Tenés un rango o reputación en tu ejército. Tu conocimiento táctico y conexiones militares son puertas abiertas.",
                            Nombre = "Soldado"
                        },
                        new
                        {
                            Id = 11,
                            Caracteristica = "Secretos de la ciudad",
                            Descripcion = "Naciste o creciste en calles, callejones o tejados. Pertenecés a bandas, conocés atajos urbanos y sabés el valor de permanecer invisible. La ciudad te acepta como uno de los suyos.",
                            Nombre = "Urchin (Huérfano urbano)"
                        },
                        new
                        {
                            Id = 12,
                            Caracteristica = "Actuación pública",
                            Descripcion = "Tus actos cautivan multitudes: canto, actuación, pantomima o música. Tenés presencia escénica, facilidad para atraer a la audiencia y dejar una impresión memorable.",
                            Nombre = "Entretenedor"
                        },
                        new
                        {
                            Id = 13,
                            Caracteristica = "Amigo de la naturaleza",
                            Descripcion = "Creciste entre bosques, montañas o tierras alejadas. Sabés rastrear, encontrar comida y sobrevivir sin civilización. Te mueves con naturalidad en terrenos salvajes donde otros se pierden.",
                            Nombre = "Explorador forastero"
                        },
                        new
                        {
                            Id = 14,
                            Caracteristica = "Resistencia rural",
                            Descripcion = "Labraste la tierra desde niño, y el trabajo duro te dio resistencia corporal y mental. Conocés vetas de agua, estaciones y ciclos naturales. Tu comunidad te respeta por saber mantenerla viva.",
                            Nombre = "Granjero"
                        },
                        new
                        {
                            Id = 15,
                            Caracteristica = "Alerta constante",
                            Descripcion = "Custodiás murallas, rutas o aldeas. Estás entrenado para detectar amenazas, señalarlas y actuar rápido. Pertenecés a un servicio comunitario y sabés mantener el orden.",
                            Nombre = "Guardia"
                        },
                        new
                        {
                            Id = 16,
                            Caracteristica = "Mapa y magia",
                            Descripcion = "Explorás lugares desconocidos con herramientas y magia elemental (druídica o arcana). Sabés orientarte, leer mapas y guiar a otros en rutas inexploradas con precisión y asombro.",
                            Nombre = "Guía/cartógrafo"
                        });
                });

            modelBuilder.Entity("EldaraaApi.Models.TrasfondoHabilidad", b =>
                {
                    b.Property<int>("TrasfondoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrasfondoId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("TrasfondosHabilidad");

                    b.HasData(
                        new
                        {
                            TrasfondoId = 1,
                            HabilidadId = 14
                        },
                        new
                        {
                            TrasfondoId = 1,
                            HabilidadId = 12
                        },
                        new
                        {
                            TrasfondoId = 2,
                            HabilidadId = 4
                        },
                        new
                        {
                            TrasfondoId = 2,
                            HabilidadId = 8
                        },
                        new
                        {
                            TrasfondoId = 3,
                            HabilidadId = 15
                        },
                        new
                        {
                            TrasfondoId = 3,
                            HabilidadId = 4
                        },
                        new
                        {
                            TrasfondoId = 4,
                            HabilidadId = 17
                        },
                        new
                        {
                            TrasfondoId = 4,
                            HabilidadId = 8
                        },
                        new
                        {
                            TrasfondoId = 5,
                            HabilidadId = 3
                        },
                        new
                        {
                            TrasfondoId = 5,
                            HabilidadId = 16
                        },
                        new
                        {
                            TrasfondoId = 6,
                            HabilidadId = 13
                        },
                        new
                        {
                            TrasfondoId = 6,
                            HabilidadId = 12
                        },
                        new
                        {
                            TrasfondoId = 7,
                            HabilidadId = 9
                        },
                        new
                        {
                            TrasfondoId = 7,
                            HabilidadId = 14
                        },
                        new
                        {
                            TrasfondoId = 8,
                            HabilidadId = 3
                        },
                        new
                        {
                            TrasfondoId = 8,
                            HabilidadId = 11
                        },
                        new
                        {
                            TrasfondoId = 9,
                            HabilidadId = 2
                        },
                        new
                        {
                            TrasfondoId = 9,
                            HabilidadId = 5
                        },
                        new
                        {
                            TrasfondoId = 10,
                            HabilidadId = 3
                        },
                        new
                        {
                            TrasfondoId = 10,
                            HabilidadId = 6
                        },
                        new
                        {
                            TrasfondoId = 11,
                            HabilidadId = 15
                        },
                        new
                        {
                            TrasfondoId = 11,
                            HabilidadId = 8
                        },
                        new
                        {
                            TrasfondoId = 12,
                            HabilidadId = 17
                        },
                        new
                        {
                            TrasfondoId = 12,
                            HabilidadId = 1
                        },
                        new
                        {
                            TrasfondoId = 13,
                            HabilidadId = 16
                        },
                        new
                        {
                            TrasfondoId = 13,
                            HabilidadId = 3
                        },
                        new
                        {
                            TrasfondoId = 14,
                            HabilidadId = 10
                        },
                        new
                        {
                            TrasfondoId = 14,
                            HabilidadId = 16
                        },
                        new
                        {
                            TrasfondoId = 15,
                            HabilidadId = 11
                        },
                        new
                        {
                            TrasfondoId = 15,
                            HabilidadId = 3
                        },
                        new
                        {
                            TrasfondoId = 16,
                            HabilidadId = 10
                        },
                        new
                        {
                            TrasfondoId = 16,
                            HabilidadId = 16
                        });
                });

            modelBuilder.Entity("EldaraaApi.Models.AtributoPersonalizado", b =>
                {
                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany("AtributosPersonalizados")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.EntradaLibre", b =>
                {
                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany("EntradasLibres")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.EstadisticasCombate", b =>
                {
                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.Personaje", b =>
                {
                    b.HasOne("EldaraaApi.Models.Clase", "Clase")
                        .WithMany("Personajes")
                        .HasForeignKey("ClaseId");

                    b.HasOne("EldaraaApi.Models.Raza", "Raza")
                        .WithMany("Personajes")
                        .HasForeignKey("RazaId");

                    b.HasOne("EldaraaApi.Models.Subraza", "Subraza")
                        .WithMany("Personajes")
                        .HasForeignKey("SubrazaId");

                    b.HasOne("EldaraaApi.Models.Trasfondo", "Trasfondo")
                        .WithMany("Personajes")
                        .HasForeignKey("TrasfondoId");

                    b.Navigation("Clase");

                    b.Navigation("Raza");

                    b.Navigation("Subraza");

                    b.Navigation("Trasfondo");
                });

            modelBuilder.Entity("EldaraaApi.Models.PersonajeEquipamiento", b =>
                {
                    b.HasOne("EldaraaApi.Models.Equipamiento", "Equipamiento")
                        .WithMany("PersonajesEquipamiento")
                        .HasForeignKey("EquipamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamiento");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.PersonajeHabilidad", b =>
                {
                    b.HasOne("EldaraaApi.Models.Habilidad", "Habilidad")
                        .WithMany("PersonajesHabilidad")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.PersonajeHechizo", b =>
                {
                    b.HasOne("EldaraaApi.Models.Hechizo", "Hechizo")
                        .WithMany("PersonajesHechizo")
                        .HasForeignKey("HechizoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hechizo");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.PuntuacionHabilidades", b =>
                {
                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.RasgosPersonalidad", b =>
                {
                    b.HasOne("EldaraaApi.Models.Personaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EldaraaApi.Models.Subraza", b =>
                {
                    b.HasOne("EldaraaApi.Models.Raza", "Raza")
                        .WithMany("Subrazas")
                        .HasForeignKey("RazaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("EldaraaApi.Models.TrasfondoHabilidad", b =>
                {
                    b.HasOne("EldaraaApi.Models.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EldaraaApi.Models.Trasfondo", "Trasfondo")
                        .WithMany()
                        .HasForeignKey("TrasfondoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Trasfondo");
                });

            modelBuilder.Entity("EldaraaApi.Models.Clase", b =>
                {
                    b.Navigation("Personajes");
                });

            modelBuilder.Entity("EldaraaApi.Models.Equipamiento", b =>
                {
                    b.Navigation("PersonajesEquipamiento");
                });

            modelBuilder.Entity("EldaraaApi.Models.Habilidad", b =>
                {
                    b.Navigation("PersonajesHabilidad");
                });

            modelBuilder.Entity("EldaraaApi.Models.Hechizo", b =>
                {
                    b.Navigation("PersonajesHechizo");
                });

            modelBuilder.Entity("EldaraaApi.Models.Personaje", b =>
                {
                    b.Navigation("AtributosPersonalizados");

                    b.Navigation("EntradasLibres");
                });

            modelBuilder.Entity("EldaraaApi.Models.Raza", b =>
                {
                    b.Navigation("Personajes");

                    b.Navigation("Subrazas");
                });

            modelBuilder.Entity("EldaraaApi.Models.Subraza", b =>
                {
                    b.Navigation("Personajes");
                });

            modelBuilder.Entity("EldaraaApi.Models.Trasfondo", b =>
                {
                    b.Navigation("Personajes");
                });
#pragma warning restore 612, 618
        }
    }
}
